# Generated by Django 4.0.2 on 2022-02-28 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_date_alter_expensedetail_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetail',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_detail', to='expense.expensedetail'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 13, 55, 30, 429816, tzinfo=utc)),
        ),
    ]
