# Generated by Django 4.0.2 on 2022-02-28 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_remove_expensedetail_expense_expense_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='detail',
        ),
        migrations.AddField(
            model_name='expensedetail',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_detail', to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 13, 59, 2, 807553, tzinfo=utc)),
        ),
    ]
