# Generated by Django 4.0.2 on 2022-02-28 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_remove_expense_detail_expensedetail_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 14, 56, 9, 658109, tzinfo=utc)),
        ),
    ]
