# Generated by Django 4.0.2 on 2022-03-02 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 15, 5, 31, 524095, tzinfo=utc)),
        ),
    ]
